server {
        listen       80; #前端项目的端口
        server_name  localhost;
        client_body_buffer_size 100M;
        client_max_body_size 100M;
        proxy_buffers 32 4m; # 提高缓冲区大小 分配 32 个缓冲区 最多占用 32 × 4MB = 128MB 的内存
        proxy_buffer_size 128k; # 增加头部缓冲区大小
        proxy_request_buffering off; # 对于大文件上传，可以禁用请求体缓冲
        location / {
            alias   /data/nginx/html/; #vue前端项目打包后的dist文件夹的地址的路径
            index  index.html index.htm;
            try_files $uri $uri/ /zhaocai/index.html;
        }


        location /jituan/ {
            rewrite ^/jituan(/.*)$ $1 break; # 移除 jituan 前缀 跳转集团端
            proxy_pass http://192.168.240.5:30005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /zhaocai/minio/ {
            rewrite ^/zhaocai/minio/(.*)$ /$1 break;
            proxy_pass http://192.168.241.107:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_body_buffer_size 100M;
            client_max_body_size 100M;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        location  /prod-api/{
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_body_buffer_size 100M;
            client_max_body_size 100M;
            proxy_buffering off;
            proxy_pass http://gatewaybackend:8080/;       #后台项目的运行端口
        }
        location /dev-api/{
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_body_buffer_size 100M;
            client_max_body_size 100M;
            proxy_buffering off;
            proxy_pass http://gatewaybackend:8080/;       #后台项目的运行端口
        }


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
}
