from app.models.market_data import (
    DataFetchLog,
    DataInterface,
    DataSource,
    DataSyncLog,
    StockFinancialReport,
    StockKline,
    StockNotice,
    StockNews,
    StockRealtimeQuote,
    StockSymbol,
    WatchlistItem,
)
from app.models.ai_hub import (
    AgentChildLink,
    AgentDataAssetLink,
    AgentDataSourceLink,
    AgentDefinition,
    AgentKnowledgeBaseLink,
    AgentSkillLink,
    AgentDataAsset,
    KnowledgeBase,
    KnowledgeGraph,
    GovernanceRun,
    KnowledgeDocument,
    KnowledgeEntity,
    KnowledgeRelation,
    ResearchReportRecord,
    PredictionLedger,
    SkillOptimizationDraft,
    ModelCallLog,
    ModelInstance,
    ModelProvider,
    ModelRouteRule,
    ModelSkill,
    ModelSkillRevision,
)
from app.models.schema_catalog import DatabaseTableComment
from app.models.pipeline import PipelineRun, PipelineStageRun, ScheduledJob
from app.db.base import Base
from app.db.table_comments import apply_table_comments

apply_table_comments(Base.metadata)

__all__ = [
    "DataFetchLog",
    "DataInterface",
    "DataSource",
    "DataSyncLog",
    "StockFinancialReport",
    "StockKline",
    "StockNotice",
    "StockNews",
    "StockRealtimeQuote",
    "StockSymbol",
    "WatchlistItem",
    "ResearchReportRecord",
    "PredictionLedger",
    "SkillOptimizationDraft",
    "ModelCallLog",
    "ModelInstance",
    "ModelProvider",
    "ModelRouteRule",
    "ModelSkill",
    "ModelSkillRevision",
    "AgentDefinition",
    "AgentChildLink",
    "AgentSkillLink",
    "AgentDataAssetLink",
    "AgentDataSourceLink",
    "AgentKnowledgeBaseLink",
    "AgentDataAsset",
    "KnowledgeBase",
    "KnowledgeGraph",
    "GovernanceRun",
    "KnowledgeDocument",
    "KnowledgeEntity",
    "KnowledgeRelation",
    "DatabaseTableComment",
    "PipelineRun",
    "PipelineStageRun",
    "ScheduledJob",
]
