
CREATE TABLE `tb_expert_change` (
                             `id` bigint DEFAULT NULL COMMENT 'id',
                             `expert_id` bigint DEFAULT NULL COMMENT '专家 id',
                             `expert_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '专家姓名',
                             `expert_phone` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '专家手机号码',
                             `belong_organization` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '所属组织机构',
                             `department` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '工作部门',
                             `education_degree` int DEFAULT NULL COMMENT '学历',
                             `major` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '专业',
                             `business_type` int DEFAULT NULL COMMENT '业态',
                             `expert_type` int DEFAULT NULL COMMENT '专家类别（1技术类 2经济类）',
                             `expert_state` int DEFAULT '0' COMMENT '专家状态(0账号审批中|1启用|2禁用)',
                             `user_id` bigint DEFAULT NULL COMMENT '对应用户id',
                             `create_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '创建人',
                             `create_id` bigint DEFAULT NULL COMMENT '创建人 id',
                             `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                             `update_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '修改人',
                             `update_id` bigint DEFAULT NULL COMMENT '修改人 id',
                             `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                             `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
                             `registered_certificate` int DEFAULT NULL COMMENT '执业资格证',
                             `registered_certificate_date` datetime DEFAULT NULL COMMENT '执业资格证取得时间',
                             `present_job` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '现从事专业工作',
                             `present_job_date` datetime DEFAULT NULL COMMENT '本专业参加工作时间',
                             `technical_titles` int DEFAULT NULL COMMENT '技术职称（初级、中级、副高、正高、教授级高工、研究员）',
                             `technical_titles_date` datetime DEFAULT NULL COMMENT '技术职称获取时间',
                             `present_unit_dept` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '现工作单位或者部门',
                             `email` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '邮箱',
                             `profession_resume` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '相关专业工作简历',
                             `state` int DEFAULT NULL COMMENT '审批状态',
                             `wf_process_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例 id',
                             `process_type` int DEFAULT NULL COMMENT '流程类型',
                             `operate_comment` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '审批批语'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='专家';
