# 2024.10.12 下午19:30 合同-购买材料合同清单 新增表
CREATE TABLE `contract_list_materials`  (
  `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `unique_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '唯一id',
  `con_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '合同ID',
  `subject_dtl_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目编码',
  `subject_dtl_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目名称',
  `specs` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '规格型号（特征描述）',
  `measure_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计量单位，如m³',
  `brand` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '品牌',
  `subject_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目档案ID,关联xxx表',
  `subject_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目编码',
  `subject_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目名称',
  `cost_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '价款类型(1-固定价 2-浮动价)',
  `surplus_quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '可使用数量（快照）',
  `quantity` decimal(12, 2) NULL DEFAULT 0.00 COMMENT '数量（工程量）',
  `order_quantity` decimal(12, 2) NULL DEFAULT 0.00 COMMENT '已下订单数量（工程量）：采购订单回写',
  `tax_rate` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税率',
  `ntax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（不含税）',
  `tax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（含税）,=单价（不含税）*（1+增值税率）=单价（含税）',
  `ntax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（不含税）',
  `tax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（含税）',
  `tax` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税额，单价（不含税）*税率，自动算出来的不可以更改',
  `remark` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建人id',
  `create_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `valid` int NOT NULL DEFAULT 0 COMMENT '删除状态（0-生效 其他删除）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '合同-购买材料合同清单' ROW_FORMAT = Dynamic;

# 2024.10.12 下午19:32 合同-劳务合同清单 新增表
CREATE TABLE `contract_list_labor`  (
  `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `unique_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '唯一id',
  `con_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '合同ID',
  `subject_dtl_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目编码',
  `subject_dtl_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目名称',
  `specs` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '特征描述',
  `measure_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计量单位，如m³',
  `metrological_rules` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计量规则，如按体积计算',
  `basic_job` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '工作内容',
  `subject_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目档案ID,关联xxx表',
  `subject_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目编码',
  `subject_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目名称',
  `surplus_quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '可使用工程量（快照）',
  `quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '工程量',
  `tax_rate` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税率',
  `ntax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（不含税）',
  `tax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（含税）,=单价（不含税）*（1+增值税率）=单价（含税）',
  `ntax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（不含税）',
  `tax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（含税）',
  `tax` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税额，单价（不含税）*税率，自动算出来的不可以更改',
  `settle_status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0' COMMENT '结算状态（0-未结算，1-部分结算，2-已结算）',
  `remark` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建人id',
  `create_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `valid` int NOT NULL DEFAULT 0 COMMENT '删除状态（0-生效 其他删除）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '合同-劳务合同清单' ROW_FORMAT = Dynamic;

# 2024.10.12 下午19:34 合同-其他合同清单 新增表
CREATE TABLE `contract_list_other`  (
  `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `unique_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '唯一id',
  `con_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '合同ID',
  `subject_dtl_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目编码',
  `subject_dtl_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目名称',
  `specs` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '特征描述',
  `measure_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计量单位，如m³',
  `subject_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目档案ID,关联xxx表',
  `subject_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目编码',
  `subject_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目名称',
  `surplus_quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '可使用数量（快照）',
  `quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '工程量',
  `tax_rate` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税率',
  `ntax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（不含税）',
  `tax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（含税）,=单价（不含税）*（1+增值税率）=单价（含税）',
  `ntax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（不含税）',
  `tax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（含税）',
  `tax` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税额，单价（不含税）*税率，自动算出来的不可以更改',
  `remark` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建人id',
  `create_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `valid` int NOT NULL DEFAULT 0 COMMENT '删除状态（0-生效 其他删除）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '合同-其他合同清单' ROW_FORMAT = Dynamic;

# 2024.10.12 下午19:36 合同-专业分包合同清单 新增表
CREATE TABLE `contract_list_specialty`  (
  `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `unique_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '唯一id',
  `con_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '合同ID',
  `subject_dtl_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目编码',
  `subject_dtl_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目名称',
  `specs` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '特征描述',
  `measure_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计量单位，如m³',
  `metrological_rules` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计量规则，如按体积计算',
  `basic_job` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '工作内容',
  `subject_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目档案ID,关联xxx表',
  `subject_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目编码',
  `subject_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目名称',
  `surplus_quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '可使用工程量（快照）',
  `quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '工程量',
  `tax_rate` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税率',
  `ntax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（不含税）',
  `tax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（含税）,=单价（不含税）*（1+增值税率）=单价（含税）',
  `ntax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（不含税）',
  `tax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（含税）',
  `tax` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税额，单价（不含税）*税率，自动算出来的不可以更改',
  `remark` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建人id',
  `create_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `valid` int NOT NULL DEFAULT 0 COMMENT '删除状态（0-生效 其他删除）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '合同-专业分包合同清单' ROW_FORMAT = Dynamic;

# 2024.10.12 下午19:38 合同-租赁材料合同清单 新增表
CREATE TABLE `contract_list_leased_materials`  (
  `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `unique_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '唯一id',
  `con_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '合同ID',
  `subject_dtl_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目编码',
  `subject_dtl_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目名称',
  `specs` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '规格型号（特征描述）',
  `measure_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计量单位，如m³',
  `brand` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '品牌',
  `rent_mode` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '租赁方式(1-日 2-月租 3-工作量)',
  `rent_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计租单位(1-㎡ 2-m³ 3-次)只有租赁方式是工作量时选择',
  `subject_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目档案ID,关联xxx表',
  `subject_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目编码',
  `subject_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目名称',
  `surplus_quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '可数量（快照）',
  `number` decimal(12, 2) NOT NULL DEFAULT 0.00 COMMENT '数量',
  `rent_time` decimal(12, 2) NOT NULL DEFAULT 0.00 COMMENT '租赁时间',
  `quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '工程量',
  `used_quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '已进场工程量：回写',
  `tax_rate` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税率',
  `ntax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（不含税）',
  `tax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（含税）,=单价（不含税）*（1+增值税率）=单价（含税）',
  `ntax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（不含税）',
  `tax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（含税）',
  `tax` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税额，单价（不含税）*税率，自动算出来的不可以更改',
  `remark` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建人id',
  `create_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `valid` int NOT NULL DEFAULT 0 COMMENT '删除状态（0-生效 其他删除）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '合同-租赁材料合同清单' ROW_FORMAT = Dynamic;

# 2024.10.12 下午19:40 合同-租赁设备合同清单 新增表
CREATE TABLE `contract_list_leased_device`  (
  `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `unique_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '唯一id',
  `con_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '合同ID',
  `subject_dtl_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目编码',
  `subject_dtl_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本子目名称',
  `specs` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '规格型号（特征描述）',
  `measure_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计量单位，如m³',
  `brand` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '品牌',
  `rent_mode` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '租赁方式(1-日 2-月租 3-工作量)',
  `rent_unit` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '计租单位(1-㎡ 2-m³ 3-次)只有租赁方式是工作量时选择',
  `subject_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目档案ID,关联xxx表',
  `subject_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目编码',
  `subject_name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '成本科目名称',
  `surplus_quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '可使用数量（快照）',
  `number` decimal(12, 2) NOT NULL DEFAULT 0.00 COMMENT '数量',
  `rent_time` decimal(12, 2) NOT NULL DEFAULT 0.00 COMMENT '租赁时间',
  `quantity` decimal(10, 2) NULL DEFAULT 0.00 COMMENT '工程量',
  `tax_rate` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税率',
  `ntax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（不含税）',
  `tax_price` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '单价（含税）,=单价（不含税）*（1+增值税率）=单价（含税）',
  `ntax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（不含税）',
  `tax_amount` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '金额（含税）',
  `tax` decimal(16, 4) NULL DEFAULT 0.0000 COMMENT '税额，单价（不含税）*税率，自动算出来的不可以更改',
  `remark` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `create_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建人id',
  `create_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `valid` int NOT NULL DEFAULT 0 COMMENT '删除状态（0-生效 其他删除）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '合同-租赁设备合同清单' ROW_FORMAT = Dynamic;