<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.zhaocai</groupId>
        <artifactId>zhaocai</artifactId>
        <version>3.6.4</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>zhaocai-archives</module>
        <module>zhaocai-system</module>
        <module>zhaocai-gen</module>
        <module>zhaocai-job</module>
        <module>zhaocai-file</module>
        <module>zhaocai-business</module>
    </modules>

    <artifactId>zhaocai-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        zhaocai-modules业务模块
    </description>

</project>
