"""Single source of truth for human-readable database table descriptions."""

from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import MetaData, Table
from sqlalchemy.orm import Session


@dataclass(frozen=True)
class TableDescription:
    display_name: str
    domain: str
    description: str


TABLE_DESCRIPTIONS: dict[str, TableDescription] = {
    "data_quality_rule": TableDescription("数据质量规则", "数据治理", "保存版本化质量规则、适用资产范围、严重程度、阈值和生命周期状态。"),
    "data_quality_run": TableDescription("数据质量运行", "数据治理", "记录针对数据资产、数据集版本或知识对象的一次质量检查批次及质量门禁结果。"),
    "data_quality_issue": TableDescription("数据质量问题", "数据治理", "保存质量规则发现的缺失、错误或风险问题、证据、处置状态与解决说明。"),
    "agent_execution_run": TableDescription("Agent 执行记录", "智能体", "记录 Agent 实际执行时使用的版本、模型、Skill、资产、知识版本、输入输出哈希和证据。"),
    "skill_execution_run": TableDescription("Skill 执行记录", "智能体", "记录受控 Skill 的版本、幂等键、重试、输入输出、写入范围、副作用和证据。"),
    "classification_definition": TableDescription("\u5206\u7c7b\u4e3b\u6570\u636e\u5b9a\u4e49", "\u6570\u636e\u5e95\u5ea7", "\u884c\u4e1a\u3001\u4e3b\u9898\u3001\u7c7b\u578b\u548c\u89c4\u6a21\u6807\u7b7e\u7684\u7248\u672c\u5316\u4e3b\u6570\u636e\u53ca\u5176\u771f\u5b9e\u91ca\u4e49\uff0c\u7528\u4e8e\u524d\u7aef\u89e3\u91ca\u548c\u5206\u7c7b\u6cbb\u7406\u3002"),
    "foundation_source_identity": TableDescription("来源主体标识", "数据底座", "将来源命名空间及稳定发行人标识映射到主体，支持有依据的跨市场同公司关联，不按名称合并。"),
    "foundation_company_mapping_state": TableDescription("股票公司映射覆盖", "数据底座", "保存各股票发行公司映射的结果、依据及未覆盖原因，不改变既有股票主数据。"),
    "foundation_security_classification": TableDescription("证券分类事实", "数据底座", "直接关联证券、定义版本及证据的分类候选，独立记录业务有效期和审核历史，不强挂发行公司。"),
    "foundation_entity": TableDescription("主数据主体", "数据底座", "保存公司、人物、机构及分类等稳定身份，外部标识在法域内唯一，同名不自动合并。"),
    "foundation_security": TableDescription("主数据证券", "数据底座", "保存独立证券身份、发行公司和股份类别，与上市记录分离。"),
    "foundation_listing": TableDescription("证券上市映射", "数据底座", "将既有股票记录映射到证券及发行公司，保留市场代码和持久证据。"),
    "foundation_evidence": TableDescription("持久证据版本", "数据底座", "独立保存来源文本及版本，不受旧知识图谱重建影响，保留可获知时间和内容范围。"),
    "foundation_fact": TableDescription("主数据候选事实", "数据底座", "保存股权、控制、经济往来、分类及司法参与事实，使用审核状态和业务有效期。"),
    "foundation_fact_evidence": TableDescription("事实证据关联", "数据底座", "关联事实与不可变证据版本，一项事实可由多份证据支持。"),
    "foundation_fact_review": TableDescription("事实审核历史", "数据底座", "追加记录事实状态变化、理由和操作标识，支持按系统知晓时刻回放。"),
    "stock_context_event": TableDescription("股票外部证据", "数据采集", "保存人工补充的政策、原材料、产业链、股东及合同原文和来源，关联股票后供知识治理使用。"),
    "pipeline_run": TableDescription("工作流运行记录", "任务编排", "记录一次业务工作流的触发来源、输入输出、当前阶段、执行状态和错误。"),
    "pipeline_stage_run": TableDescription("工作流阶段记录", "任务编排", "记录工作流内各阶段的尝试次数、租约、重试计划、输入输出和错误。"),
    "scheduled_job": TableDescription("后台任务队列", "任务编排", "保存独立 Worker 消费的幂等任务、执行时间、租约、重试次数和处理状态。"),
    "agent_child_link": TableDescription("智能体子任务关系", "智能体", "记录主智能体与子智能体的编排关系及执行顺序。"),
    "agent_data_asset": TableDescription("智能体数据资产", "数据治理", "登记可供智能体访问的本地数据表、允许字段、治理状态及启停状态。"),
    "agent_data_asset_link": TableDescription("智能体数据资产绑定", "智能体", "记录智能体与可访问数据资产的多对多授权关系。"),
    "agent_data_source_link": TableDescription("智能体数据源绑定", "智能体", "记录智能体与可调用数据源的多对多绑定关系。"),
    "agent_definition": TableDescription("智能体定义", "智能体", "保存智能体的提示词、模型实例、迭代上限、上下文限制及结构化输出约束。"),
    "agent_knowledge_base_link": TableDescription("智能体知识库绑定", "智能体", "记录智能体与可查询知识库的多对多绑定关系。"),
    "agent_skill_link": TableDescription("智能体 Skill 绑定", "智能体", "记录智能体可调用的 Skill 及其绑定关系。"),
    "data_fetch_log": TableDescription("按需数据抓取日志", "数据采集", "记录按股票和接口抓取数据的请求、结果数量、落库数量及错误。"),
    "data_interface": TableDescription("数据接口目录", "数据采集", "登记数据源提供的接口、适用市场、调用方式及输入输出结构。"),
    "data_source": TableDescription("数据源", "数据采集", "登记行情和资讯数据供应源、适配器类型、优先级及启用配置。"),
    "data_sync_log": TableDescription("批量同步日志", "数据采集", "记录股票基础资料等批量同步任务的市场、状态和增删改统计。"),
    "database_table_comment": TableDescription("数据库表说明", "系统元数据", "保存各表的中文名称、业务用途和字段释义，供 SQLite 客户端直接查询。"),
    "governance_run": TableDescription("治理执行记录", "数据治理", "记录数据资产或知识图谱的一次治理任务、所用智能体、来源资产及结果。"),
    "knowledge_base": TableDescription("知识库", "知识图谱", "登记知识库的来源表、版本、状态，以及实体和关系统计。"),
    "knowledge_document": TableDescription("知识文档", "知识图谱", "保存由源数据转化的知识文档，并关联知识库、图谱和股票代码。"),
    "knowledge_entity": TableDescription("知识实体", "知识图谱", "保存知识图谱中的公司、人物、事件等实体及其属性。"),
    "knowledge_graph": TableDescription("知识图谱", "知识图谱", "登记知识库下的独立图谱、股票范围、来源表、治理与启用状态。"),
    "knowledge_relation": TableDescription("知识关系", "知识图谱", "保存实体之间的关系、谓词及可追溯的证据文档。"),
    "model_call_log": TableDescription("模型调用日志", "模型实验室", "记录模型请求、响应、耗时、状态及错误，供调试和审计。"),
    "model_instance": TableDescription("模型实例", "模型实验室", "保存供应商下具体模型的用途、调用地址、参数与备用实例。"),
    "model_provider": TableDescription("模型供应商", "模型实验室", "保存模型供应商类型、API 地址、加密凭据和启用状态。"),
    "model_route_rule": TableDescription("模型任务路由", "模型实验室", "按任务类型配置首选模型实例、降级链及路由策略。"),
    "model_skill": TableDescription("Skill 定义", "模型实验室", "保存 Skill 指令、类型、版本、文件同步信息和启用状态。"),
    "model_skill_revision": TableDescription("Skill 历史版本", "模型实验室", "保存 Skill 每个版本的指令正文、内容哈希和变更来源，支持回滚。"),
    "prediction_ledger": TableDescription("预测账本", "研究复盘", "保存选股或买卖建议、依据与使用的 Skill 版本，并记录后续实际走势和评估。"),
    "research_report": TableDescription("研究报告", "研究复盘", "保存单只股票的 AI 研报、结论、评分、数据来源及历史报告评估。"),
    "stock_broker_research_report": TableDescription("券商研报资料", "股票研究", "按股票、公开来源和外部报告编号保存券商研报标题、评级、原文正文及来源证据。"),
    "stock_earnings_consensus": TableDescription("盈利预测共识", "股票研究", "按股票、预测年度和指标保存机构一致预期统计，保留来源及更新时间。"),
    "stock_institution_forecast": TableDescription("机构盈利预测", "股票研究", "保存单家机构按报告日披露的未来年度盈利预测，不与普通研报列表混为同一对象。"),
    "stock_investor_qa": TableDescription("投资者互动问答", "股票研究", "保存巨潮资讯互动易公开问答及其问题编号、回答、时间和原文地址。"),
    "skill_optimization_draft": TableDescription("Skill 优化草案", "研究复盘", "保存预测失败后生成的 Skill 修订建议、证据与人工审核状态。"),
    "stock_f10_cache": TableDescription("股票 F10 缓存", "股票数据", "按股票及栏目缓存 F10 公司资料和业务信息。"),
    "stock_financial_report": TableDescription("股票财务报告", "股票数据", "按股票、指标、报告期和来源保存财务报告结构化数据。"),
    "stock_kline": TableDescription("股票历史 K 线", "股票数据", "保存股票不同周期和复权口径下的开高低收、成交量额及换手率。"),
    "stock_news": TableDescription("股票新闻", "股票数据", "保存股票相关新闻的时间、标题、正文、来源和原文链接。"),
    "stock_notice": TableDescription("股票公告", "股票数据", "保存上市公司公告的日期、类型、标题、链接和结构化内容。"),
    "stock_realtime_quote": TableDescription("股票实时行情", "股票数据", "保存每只股票最新报价、涨跌幅、成交量额和行情时间。"),
    "stock_symbol": TableDescription("股票基础资料", "股票数据", "保存股票代码、市场、交易所、名称、上市状态及来源信息。"),
    "watchlist_item": TableDescription("自选股", "股票数据", "保存用户关注的市场与股票代码及备注。"),
    "selection_run": TableDescription("选股监盘运行", "选股监盘", "保存硬规则筛选运行、模型与知识库选择、候选数量和缺失数据。"),
    "selection_candidate": TableDescription("选股候选", "选股监盘", "保存硬过滤候选、量价规则、本地知识证据及人工接受或拒绝结果。"),
    "selection_tracking": TableDescription("选股跟踪", "选股监盘", "保存人工确认后的预测目标、实际交易日进度、收益、回撤和复盘状态。"),
    "selection_snapshot": TableDescription("选股跟踪快照", "选股监盘", "按实际交易日保存收盘价、累计收益和回撤，至少满十个交易日后完成复盘。"),
    "selection_decision_snapshot": TableDescription("选股决策审计快照", "选股监盘", "以不可变事件方式保存候选生成和人工审核时使用的证据、图谱版本、数据版本及 Skill 版本。"),
    "selection_retrospective": TableDescription("选股复盘版本", "选股监盘", "按市场数据刷新追加保存选股跟踪结果，保留每次复盘的状态哈希、收益、回撤和错误标签。"),
    "skill_evaluation_case": TableDescription("Skill 评测用例", "模型实验室", "保存可重复执行的黄金用例、输入、期望输出和评分规则，用于 Skill 回归验证。"),
    "skill_evaluation_run": TableDescription("Skill 评测运行", "模型实验室", "记录某个 Skill 版本在固定用例集上的评测批次、数据集版本、评测器和汇总结果。"),
    "skill_evaluation_result": TableDescription("Skill 评测结果", "模型实验室", "保存单个评测用例的实际输出、规则指标、证据引用及通过或失败状态。"),
    "lake_object": TableDescription("湖仓对象目录", "湖仓", "按内容哈希登记本地文件或 MinIO 物理对象；同一内容的不同分层、来源和数据集归属保存在逻辑绑定元数据中。"),
    "lake_dataset": TableDescription("湖仓数据集目录", "湖仓", "登记 Raw、Normalized、Serving 分层的数据集定义、存储格式、分区规范和当前版本。"),
    "lake_dataset_version": TableDescription("湖仓数据集版本", "湖仓", "保存数据集每次发布的版本、对象地址、行数、字段结构和质量检查结果。"),
    "lake_lineage_event": TableDescription("湖仓数据血缘", "湖仓", "记录数据从上游表或文档到下游对象、数据集及知识资产的转换链路和解析版本。"),
    "document_chunk_version": TableDescription("文档切片版本", "湖仓", "保存文档切片正文、原文偏移、解析器版本和向量模型版本，支持 RAG 可追溯重建。"),
}


COMMON_COLUMN_DESCRIPTIONS: dict[str, str] = {
    "attempt": "当前工作流阶段已经执行的次数。",
    "attempts": "后台任务已经执行的次数。",
    "correlation_id": "用于关联同一业务请求或跨系统调用链的标识。",
    "current_stage": "工作流当前正在执行或最近执行的阶段编码。",
    "error_code": "失败异常的类型或标准错误编码。",
    "idempotency_key": "避免相同业务任务重复创建和执行的唯一键。",
    "input_json": "工作流或阶段接收的结构化输入。",
    "lease_until": "Worker 对任务或阶段持有执行权的截止时间。",
    "max_attempts": "任务或阶段允许执行的最大次数。",
    "next_retry_at": "失败后允许再次执行的最早时间。",
    "output_json": "工作流或阶段产出的结构化结果。",
    "pipeline_run_id": "所属工作流运行记录 ID。",
    "pipeline_type": "工作流的业务类型编码。",
    "run_after": "后台任务允许开始执行的最早时间。",
    "stage_code": "工作流阶段的稳定业务编码。",
    "trigger_type": "工作流触发来源，例如 API、定时调度或人工操作。",
    "worker_id": "领取并执行后台任务的 Worker 实例标识。",
    "action_type": "预测建议的操作类型，例如买入、卖出或持有。",
    "actual_price": "复盘时观察到的实际股价。",
    "actual_return_pct": "按实际股价计算的收益率百分比。",
    "adapter_method": "数据适配器中执行该接口的方法名。",
    "adapter_type": "接入数据源所用的适配器类型。",
    "adjust": "K 线复权口径，例如前复权、后复权或不复权。",
    "agent_code": "智能体的唯一业务编码。",
    "agent_id": "关联的智能体定义 ID。",
    "agent_snapshot_json": "生成研报时使用的智能体配置快照。",
    "allowed_columns": "允许智能体访问的数据表字段名列表。",
    "amount": "成交额；计量单位以数据来源为准。",
    "api_base_url": "模型供应商或实例的 API 基础地址。",
    "api_key": "实例级 API 密钥，兼容历史配置。",
    "api_key_encrypted": "经加密保存的供应商 API 密钥。",
    "api_path": "实例调用接口相对 API 基础地址的路径。",
    "asset_code": "数据资产的唯一业务编码。",
    "asset_type": "证券资产类型，例如股票。",
    "base_skill_version": "优化建议所依据的原 Skill 版本号。",
    "change_amount": "最新价相对前收盘价的涨跌金额。",
    "change_pct": "最新价相对前收盘价的涨跌幅百分比。",
    "child_agent_id": "被编排的子智能体 ID。",
    "close_price": "该交易周期的收盘价。",
    "column_comments_json": "字段名到中文释义的 JSON 对象。",
    "completed_at": "任务或调用完成时间。",
    "conclusion": "研报的最终分析结论。",
    "config_json": "该记录的扩展配置参数，JSON 格式。",
    "content": "新闻或知识文档的正文内容。",
    "content_hash": "Skill 指令内容的哈希值，用于校验版本。",
    "content_json": "公告或新闻的结构化正文及附加信息。",
    "context_window_limit": "智能体保留的历史对话轮数上限。",
    "created_at": "记录创建时间。",
    "currency": "财务数据使用的币种。",
    "current_price": "股票最新成交价或报价。",
    "data_asset_id": "关联的数据资产 ID。",
    "data_category": "接口提供的数据类别。",
    "data_json": "财务报告或指标的结构化数据。",
    "data_source_id": "关联的数据源 ID。",
    "data_sources_json": "生成研报时使用的数据源编码列表。",
    "description": "该记录的业务说明或备注。",
    "detail_json": "同步任务的详细结果及附加统计。",
    "direction_hit": "预测方向是否与实际走势一致。",
    "display_name": "界面展示用的中文名称。",
    "domain": "表所属的业务领域。",
    "enabled": "是否启用该记录或配置。",
    "entity_count": "知识库或图谱中的实体数量。",
    "entity_key": "同一知识库内用于去重的实体键。",
    "entity_name": "知识实体的展示名称。",
    "entity_type": "知识实体类别，例如公司、人物或事件。",
    "entry_price": "生成预测建议时采用的参考入场价格。",
    "error_message": "执行失败时的错误信息。",
    "evaluated_at": "预测复盘评估完成时间。",
    "evaluation_json": "预测命中与收益率评估的详细结果。",
    "evidence_document_id": "支持该知识关系的证据文档 ID。",
    "exchange": "股票所属交易所。",
    "ext_json": "股票基础资料的扩展属性。",
    "failed_count": "批量同步失败的记录数量。",
    "failure_signature": "一组预测失败案例的去重标识。",
    "fallback_chain_json": "首选模型不可用时依次尝试的实例编码列表。",
    "fallback_instance_code": "模型实例自身配置的备用实例编码。",
    "fetched_at": "数据从来源接口获取的时间。",
    "file_path": "Skill 对应的 Markdown 文件路径。",
    "format": "Skill 文件格式，例如 MD。",
    "governance_report_json": "最近一次数据或图谱治理的结构化报告。",
    "governance_status": "治理状态，例如待治理、已治理或已锁定。",
    "graph_code": "知识图谱的唯一业务编码。",
    "graph_id": "所属知识图谱 ID。",
    "graph_name": "知识图谱的展示名称。",
    "high_price": "该交易周期的最高价。",
    "history_evaluation_json": "新研报对历史研报结论的对比评估。",
    "id": "本表记录的数字主键。",
    "indicator": "财务指标或报告类别编码。",
    "input_schema": "数据接口入参的结构定义。",
    "inserted_count": "批量同步中新插入的记录数量。",
    "instance_code": "模型实例的唯一业务编码。",
    "instructions": "Skill 当前或历史版本的指令正文。",
    "interface_code": "数据接口的业务编码。",
    "interface_name": "数据接口的展示名称。",
    "is_builtin": "是否为系统内置 Skill。",
    "json_schema_output": "智能体返回结构化 JSON 的 Schema 约束。",
    "kb_code": "知识库的唯一业务编码。",
    "kb_name": "知识库的展示名称。",
    "knowledge_base_id": "所属知识库 ID。",
    "knowledge_base_ids_json": "生成研报时使用的知识库 ID 列表。",
    "last_governed_at": "最近一次成功或尝试治理的时间。",
    "last_inspected_at": "最近一次检查数据资产的时间。",
    "last_synced_at": "股票基础资料最近同步时间。",
    "latency_ms": "模型调用耗时，单位毫秒。",
    "list_date": "股票上市日期。",
    "low_price": "该交易周期的最低价。",
    "market": "所属证券市场编码，例如 CN_A 或 HK。",
    "max_iterations": "智能体一次任务允许的最大迭代次数。",
    "max_tokens": "模型单次回答允许输出的最大 Token 数。",
    "metadata_json": "知识文档的来源及其他元数据。",
    "model_call_log_id": "关联的模型调用日志 ID。",
    "model_code": "供应商 API 使用的具体模型编码。",
    "model_instance": "生成研报时使用的模型实例编码。",
    "model_instance_code": "关联或使用的模型实例编码。",
    "model_name": "模型实例的展示名称。",
    "model_provider": "生成研报时使用的模型供应商编码。",
    "name": "股票或报告对应的证券名称。",
    "news_time": "新闻发布的日期和时间。",
    "note": "自选股备注。",
    "notice_date": "公告发布日期。",
    "notice_type": "公告业务类型。",
    "object_entity_id": "知识关系的客体实体 ID。",
    "open_price": "该交易周期的开盘价。",
    "order_index": "子智能体的执行顺序。",
    "output_schema": "数据接口返回结果的结构定义。",
    "payload_json": "F10 栏目的缓存内容。",
    "period": "K 线周期，例如日线或周线。",
    "persisted_count": "按需抓取后成功写入本地库的记录数量。",
    "predicate": "知识关系的谓词或关系类型。",
    "predicted_at": "预测建议生成时间。",
    "prediction_ids": "触发 Skill 优化建议的预测账本 ID 列表。",
    "preferred_instance_code": "该任务路由的首选模型实例编码。",
    "previous_close_price": "前一交易日收盘价。",
    "price_as_of": "复盘实际价格对应的行情时间。",
    "priority": "数据源路由优先级，数值越小越优先。",
    "properties_json": "知识实体的属性键值集合。",
    "proposed_instructions": "待审核的新版 Skill 指令草案。",
    "provider_code": "模型供应商的唯一业务编码。",
    "provider_id": "所属模型供应商 ID。",
    "provider_name": "模型供应商的展示名称。",
    "provider_type": "模型供应商协议或适配器类型。",
    "purpose": "模型实例的主要业务用途。",
    "quote_time": "实时行情报价对应的时间。",
    "rating": "研报给出的投资评级。",
    "rationale": "提出 Skill 优化草案的原因与依据。",
    "raw_payload": "数据源返回的原始报文。",
    "reasoning_logic": "选股或交易建议的推理依据。",
    "relation_count": "知识库或图谱中的关系数量。",
    "report_markdown": "完整研报正文，Markdown 格式。",
    "report_period": "财务报告所属会计期间。",
    "request_json": "发起数据抓取或模型调用时的请求参数。",
    "request_mode": "接口的请求或同步方式。",
    "research_report_id": "关联的研究报告 ID。",
    "response_json": "模型返回的结构化响应。",
    "response_text": "模型返回的文本内容。",
    "reviewed_at": "Skill 优化草案被审核的时间。",
    "route_policy": "首选实例与降级链的调度策略。",
    "row_count": "数据资产最近一次统计的记录行数。",
    "score": "研报综合评分。",
    "section": "F10 公司资料的栏目编码。",
    "skill_code": "Skill 的唯一业务编码。",
    "skill_id": "关联的 Skill ID。",
    "skill_name": "Skill 的展示名称。",
    "skill_type": "Skill 类型：提示词 SOP 或可执行工具。",
    "skill_version_used": "生成预测时实际使用的 Skill 版本。",
    "source": "记录对应的数据来源；具体口径以所属表及来源说明为准。",
    "source_asset_ids": "本次治理使用的数据资产 ID 列表。",
    "source_code": "数据源的唯一业务编码。",
    "source_health": "数据资产来源表的健康检查结果。",
    "source_id": "关联的数据源 ID。",
    "source_name": "数据来源的展示名称。",
    "source_record_id": "来源表中原始记录的 ID。",
    "source_table": "知识文档所依据的本地来源表名。",
    "source_tables": "知识库或图谱关联的来源表名列表。",
    "source_type": "数据源的业务类型。",
    "started_at": "任务或调用开始时间。",
    "status": "该记录当前的业务状态。",
    "stock_code": "股票交易代码。",
    "subject_entity_id": "知识关系的主语实体 ID。",
    "summary_json": "数据或图谱治理结果摘要。",
    "supported_markets": "该接口支持的市场编码列表。",
    "symbol": "股票交易代码。",
    "system_prompt": "智能体执行任务时使用的系统提示词。",
    "table_name": "关联的物理数据库表名。",
    "target_id": "本次治理的目标记录 ID。",
    "target_return_pct": "预测期望达到的收益率百分比。",
    "target_timeframe": "预测的目标期限，例如 T+5。",
    "target_type": "治理目标类别，例如数据资产或知识图谱。",
    "task_type": "模型调用或路由对应的任务类型。",
    "temperature": "模型生成随机性参数，越低通常越稳定。",
    "title": "新闻、公告、知识文档或研报的标题。",
    "top_p": "模型核采样概率阈值。",
    "total_count": "本次抓取或同步处理的记录总数。",
    "trade_date": "K 线对应的交易日期。",
    "turnover_rate": "股票换手率；计量口径以数据来源为准。",
    "updated_at": "记录最近更新时间。",
    "updated_count": "批量同步中更新的记录数量。",
    "url": "来源网页或原始资料链接。",
    "usage_type": "模型参数用途类型，例如精确型 EXACT 或创意型 CREATIVE。",
    "version": "当前配置或历史内容的版本号。",
    "volume": "成交量；计量单位以数据来源为准。",
    "warnings_json": "研报中的风险提示列表。",
    "as_of": "Selection evaluation timestamp",
    "candidate_count": "Number of hard-filter candidates",
    "candidate_limit": "Maximum candidate count",
    "data_mode": "Real or mock data marker",
    "graph_ids_json": "Selected knowledge graph IDs",
    "reviewed_count": "Number of manually reviewed candidates",
    "tracking_count": "Number of approved tracking records",
    "universe_scope": "Universe scope",
    "criteria_json": "Hard filter criteria",
    "analysis_mode": "Analysis mode",
    "missing_data_json": "Missing-data explanations",
    "run_id": "Selection run ID",
    "entry_date": "Entry trade date",
    "hard_score": "Deterministic hard-filter score",
    "hard_rules_json": "Deterministic rule results",
    "evidence_json": "Local evidence references",
    "analysis_json": "Bounded analysis result",
    "decision": "Human review decision",
    "review_notes": "Human review notes",
    "target_price": "Human-confirmed target price",
    "stop_price": "Human-confirmed stop price",
    "confidence": "Human-confirmed confidence",
    "prediction_id": "Prediction ledger ID",
    "candidate_id": "Candidate ID",
    "required_sessions": "Required trading sessions",
    "observed_sessions": "Observed trading sessions",
    "latest_date": "Latest observed trade date",
    "latest_price": "Latest observed close price",
    "cumulative_return_pct": "Cumulative return percentage",
    "max_drawdown_pct": "Maximum drawdown percentage",
    "data_source": "Observed data source",
    "review_json": "Tracking review result",
    "tracking_id": "Tracking ID",
    "return_pct": "Return from entry percentage",
    "drawdown_pct": "Drawdown percentage",
    "sequence": "Trading-session sequence",

    "confirmation_date": "Human review confirmation date",
    "adjust": "价格复权口径；空值表示不复权，其他口径以来源定义为准。",
    "target_hit": "Whether the confirmed target was reached after the required sessions.",
    "stop_hit": "Whether the confirmed stop level was reached during tracking.",
    "accessible_assets_json": "Agent 本次执行获得授权访问的数据资产标识列表。",
    "agent_execution_run_id": "关联的 Agent 执行记录 ID。",
    "agent_version": "本次执行快照使用的 Agent 版本。",
    "asset_scope": "质量规则适用的资产或知识对象类型。",
    "audit_json": "执行过程中的授权、策略和审计扩展信息。",
    "canonical_identity": "数据资产在统一身份体系中的规范标识。",
    "definition_json": "质量规则的可执行定义和字段配置。",
    "details_json": "质量问题的结构化上下文和诊断细节。",
    "embedding_kind": "向量类型；NONE、HASH 或 SEMANTIC，哈希向量不得标记为语义向量。",
    "embedding_status": "切片向量生成状态，例如 MISSING、HASH_ONLY、READY 或 FAILED。",
    "error_policy_json": "Skill 失败分类、停止、降级与补偿策略。",
    "evidence_ids_json": "支持运行结果或问题判断的证据标识列表。",
    "expected_value_json": "质量规则期望值、范围或约束的结构化表达。",
    "failed_rules": "本次质量运行未通过的规则数量。",
    "first_detected_at": "质量问题首次发现时间。",
    "idempotency_policy": "Skill 的幂等要求和重复请求处理方式。",
    "input_contract_json": "Skill 可接受输入字段、类型与约束的契约。",
    "input_hash": "规范化执行输入的 SHA256 哈希。",
    "issue_code": "质量问题的稳定分类编码。",
    "knowledge_version_policy_json": "Agent 访问知识库和图谱版本的选择及固定策略。",
    "knowledge_versions_json": "Agent 本次执行实际使用的知识库、图谱或数据集版本快照。",
    "lifecycle_status": "定义的生命周期状态，例如 DRAFT、TESTING、ENABLED、DISABLED 或 DEPRECATED。",
    "lineage_batch_id": "生成该切片的血缘处理批次标识。",
    "message": "质量问题或执行结果的可读说明。",
    "model_version": "本次执行实际使用的模型版本或模型编码快照。",
    "observed_value_json": "质量检查实际观测到的值或统计结果。",
    "output_contract_json": "Skill 输出字段、类型、状态和证据要求的契约。",
    "output_hash": "规范化执行输出的 SHA256 哈希。",
    "parent_run_id": "父级 Agent 执行记录 ID，用于多 Agent 调度链。",
    "passed_rules": "本次质量运行通过的规则数量。",
    "permission_policy_json": "Skill 可访问资产、允许操作和禁止能力的权限策略。",
    "pipeline_stage_run_id": "关联的工作流阶段执行记录 ID。",
    "policy_json": "Agent 的调用、工具、写入、重试和安全策略。",
    "quality_run_id": "关联的数据质量运行 ID。",
    "resolution": "质量问题的解决说明或不处理理由。",
    "resolved_at": "质量问题解决时间。",
    "retry_policy_json": "Skill 最大重试次数、退避与可重试错误配置。",
    "rule_code": "质量规则的稳定业务编码。",
    "rule_id": "关联的数据质量规则记录 ID。",
    "rule_name": "质量规则的中文展示名称。",
    "rule_type": "质量规则类型，例如完整性、唯一性、及时性或有效性。",
    "run_key": "运行记录的稳定唯一业务键。",
    "section_path_json": "切片所在章节从上级到当前级的标题路径。",
    "section_status": "章节识别状态，例如 RESOLVED、UNRESOLVED 或 PARTIAL。",
    "section_title": "切片识别出的具体章节标题。",
    "severity": "质量问题或规则的严重程度。",
    "side_effect_level": "Skill 副作用等级，例如 READ_ONLY、CONTROLLED_WRITE 或 EXTERNAL_ACTION。",
    "skill_version": "本次执行实际使用的 Skill 版本。",
    "skill_versions_json": "Agent 本次执行实际调用的 Skill 版本快照。",
    "source_object_id": "切片原文在湖仓对象目录中的对象 ID。",
    "target_code": "规则限制到具体资产或数据集时使用的业务编码。",
    "target_version": "被检查目标的数据集、文档或知识版本。",
    "threshold_json": "质量规则的通过阈值和质量门禁配置。",
    "total_rules": "本次质量运行实际执行的规则总数。",
    "warning_rules": "本次质量运行产生警告但未阻断的规则数量。",
    "write_scope_json": "受控 Skill 被允许或实际写入的资源和字段范围。",
}


TABLE_COLUMN_OVERRIDES: dict[str, dict[str, str]] = {
    "stock_broker_research_report": {
        "external_id": "公开来源中的稳定研报编号。", "report_date": "来源页面披露的研报日期。",
        "institution": "发布研报的券商或研究机构。", "analysts_json": "来源披露的分析师姓名列表。",
        "summary": "研报正文摘要，不替代完整正文。", "content_text": "从公开详情页或 PDF 提取的研报正文。",
        "content_status": "正文获取状态，例如待获取、已就绪或失败。", "fetch_error": "正文获取失败时记录的原因。",
        "source_url": "研报列表或公开来源页面地址。", "detail_url": "可直接获取研报详情正文的页面地址。",
        "pdf_url": "来源提供的研报 PDF 地址。", "source_updated_at": "来源记录自身披露或更新的时间。",
    },
    "stock_earnings_consensus": {
        "forecast_year": "盈利一致预期对应的预测年度。", "metric_code": "预测指标稳定编码，例如 EPS 或 NET_PROFIT。",
        "metric_name": "预测指标中文名称。", "unit": "预测指标展示单位。",
        "prediction_count": "参与该年度该指标预测的机构数量。", "minimum_value": "来源统计的预测最小值。",
        "mean_value": "来源统计的预测均值。", "maximum_value": "来源统计的预测最大值。",
        "industry_average": "来源提供的同行业预测平均值。", "source_url": "盈利预测公开来源页面地址。",
        "source_updated_at": "来源记录自身披露或更新的时间。",
    },
    "stock_institution_forecast": {
        "external_key": "机构、报告日和分析师组合生成的幂等业务键。", "institution": "披露预测的券商或研究机构。",
        "analysts_json": "来源披露的分析师姓名列表。", "report_date": "机构预测对应的报告日期。",
        "forecast_json": "该机构未来年度每股收益、净利润等预测值。", "report_external_id": "可选关联的外部研报编号。",
        "source_url": "机构预测公开来源页面地址。", "detail_url": "机构预测或关联报告详情页面地址。",
        "source_updated_at": "来源记录自身披露或更新的时间。",
    },
    "stock_investor_qa": {
        "external_id": "巨潮互动易问题编号。", "question": "投资者公开提问正文。",
        "answer": "上市公司公开回答正文。", "questioner": "来源披露的提问者标识。",
        "answerer": "来源披露的回答主体。", "asked_time": "问题提交时间。",
        "answered_time": "上市公司回答时间。", "updated_time": "该问答在来源中的最近更新时间。",
        "source_url": "巨潮互动易问题详情地址。", "source_updated_at": "来源记录自身披露或更新的时间。",
    },
    "lake_object": {
        "id": "湖仓对象 ID",
        "object_uri": "对象存储地址",
        "layer": "数据分层，例如 Raw、Normalized 或 Serving",
        "bucket": "对象存储桶名称",
        "object_key": "对象在存储桶中的键",
        "content_hash": "对象内容的 SHA256 哈希",
        "content_type": "对象的媒体类型或文件类型",
        "byte_size": "对象文件大小，单位为字节",
        "source_code": "来源数据源编码",
        "source_table": "来源数据表名称",
        "source_record_id": "来源记录编号",
        "dataset_version": "关联的数据集版本号",
        "metadata_json": "对象扩展元数据；logical_bindings 保留同一物理内容在不同分层、来源和数据集中的逻辑归属",
        "created_at": "对象目录记录创建时间",
    },
    "lake_dataset": {
        "id": "数据集 ID",
        "dataset_code": "数据集业务编码",
        "dataset_name": "数据集中文名称",
        "layer": "数据分层，例如 Raw、Normalized 或 Serving",
        "format": "数据集存储格式，例如 Parquet",
        "partition_spec": "数据集分区字段和分区规则",
        "description": "数据集业务说明",
        "current_version": "当前发布的数据集版本",
        "created_at": "数据集创建时间",
        "updated_at": "数据集最近更新时间",
    },
    "lake_dataset_version": {
        "id": "数据集版本 ID",
        "dataset_id": "所属数据集编号",
        "version": "数据集版本号",
        "object_id": "对应湖仓对象编号",
        "row_count": "该版本包含的数据行数",
        "schema_json": "该版本的字段结构定义",
        "quality_json": "该版本的数据质量检查结果",
        "status": "版本状态，例如已发布或已废弃",
        "created_at": "数据集版本创建时间",
    },
    "lake_lineage_event": {
        "id": "血缘事件 ID",
        "batch_id": "处理批次编号",
        "upstream_type": "上游对象类型",
        "upstream_id": "上游对象编号",
        "downstream_type": "下游对象类型",
        "downstream_id": "下游对象编号",
        "transformation": "执行的数据转换步骤",
        "parser_version": "解析器或转换程序版本",
        "dataset_version": "关联的数据集版本号",
        "metadata_json": "血缘事件扩展元数据",
        "created_at": "血缘事件创建时间",
    },
    "document_chunk_version": {
        "id": "文档切片 ID",
        "document_key": "文档稳定业务键",
        "document_id": "关联的知识文档编号",
        "chunk_index": "切片在文档中的顺序编号",
        "chunk_version": "切片版本号",
        "content_hash": "切片正文的 SHA256 哈希",
        "chunk_text": "切片正文内容",
        "start_offset": "切片在原文中的起始字符位置",
        "end_offset": "切片在原文中的结束字符位置",
        "parser_version": "文档解析器版本",
        "embedding_model": "生成向量时使用的模型版本",
        "status": "切片状态，例如就绪或废弃",
        "metadata_json": "切片的扩展元数据",
        "created_at": "切片版本创建时间",
    },
    "foundation_company_mapping_state": {
        "stock_symbol_id": "既有股票主数据的记录标识。", "status": "发行公司映射结果；未映射不表示公司不存在。",
        "reason": "映射成功、待补充或暂不支持的具体原因。", "source_name": "本次映射使用的来源名称。",
        "source_snapshot": "用于核对映射依据的来源快照标识或链接。", "attempt_count": "累计尝试映射次数。",
        "details_json": "映射过程的业务依据、识别结果及待补充信息。", "attempted_at": "最近一次尝试建立映射的时间。",
    },
    "classification_definition": {
        "id": "\u5206\u7c7b\u5b9a\u4e49\u7a33\u5b9a ID", "taxonomy": "\u5206\u7c7b\u4f53\u7cfb\u540d\u79f0", "dimension": "\u5206\u7c7b\u7ef4\u5ea6\uff0c\u5982\u884c\u4e1a\u3001\u4e3b\u9898\u3001\u7c7b\u578b", "code": "\u6765\u6e90\u6216\u8bcd\u5178\u4ee3\u7801", "label": "\u663e\u793a\u540d\u79f0", "definition": "\u4e3b\u6570\u636e\u771f\u5b9e\u91ca\u4e49", "criteria": "\u7eb3\u5165\u6807\u51c6\u548c\u4e0d\u9002\u7528\u8bf4\u660e", "parent_code": "\u4e0a\u7ea7\u5206\u7c7b\u4ee3\u7801", "jurisdiction": "\u9002\u7528\u6cd5\u57df", "source_name": "\u5b9a\u4e49\u6765\u6e90", "source_url": "\u6765\u6e90\u94fe\u63a5", "definition_version": "\u91ca\u4e49\u7248\u672c", "status": "\u5b9a\u4e49\u72b6\u6001", "valid_from": "\u6709\u6548\u671f\u5f00\u59cb", "valid_to": "\u6709\u6548\u671f\u7ed3\u675f", "properties_json": "\u6269\u5c55\u5c5e\u6027", "created_at": "\u521b\u5efa\u65f6\u95f4", "updated_at": "\u66f4\u65b0\u65f6\u95f4",
    },
    "foundation_source_identity": {
        "id": "标识映射的稳定 ID。", "entity_id": "规范主体 ID。", "namespace": "原始来源或登记体系命名空间。",
        "external_id": "来源内的稳定发行人或登记标识，不使用名称生成。", "entity_type": "标识对应主体类别。",
        "jurisdiction": "已知注册法域。", "created_at": "首次记录该映射的时刻。",
    },
    "foundation_security_classification": {
        "id": "分类事实稳定 ID。", "security_id": "直接关联的证券 ID。", "evidence_id": "支持分类的持久证据版本。",
        "dimension": "规模、风格、上市属性等分类维度。", "code": "定义体系内分类代码。", "label": "分类展示名称。",
        "definition_version": "分类定义版本。", "method": "形成分类所用方法或规则。", "properties_json": "样本、指标或规则口径。",
        "status": "候选、接受或拒绝状态。", "valid_from": "有效期开始，含当天。", "valid_to": "有效期截止，不含当天。",
        "reviews_json": "按实际发生顺序追加的审核记录。", "created_at": "首次记录时间。", "updated_at": "最近审核时间。",
    },
    "foundation_entity": {
        "id": "主体的稳定 UUID 标识。", "name": "主体名称，同名不表示同一主体。",
        "entity_type": "主体类型，例如公司、机构、人物或分类。", "jurisdiction": "主体所属注册或身份法域。",
        "identifier_scheme": "外部标识体系，例如统一社会信用代码。", "identifier_value": "指定法域及体系中的标识值。",
        "properties_json": "主体补充属性，不作为名称自动合并依据。", "created_at": "系统首次记录此主体的时刻。",
    },
    "foundation_security": {
        "id": "证券的稳定 UUID 标识。", "entity_id": "发行公司的主数据主体 ID。",
        "share_class": "股份类别，不等于股票代码或公司身份。", "created_at": "系统首次记录证券的时刻。",
    },
    "foundation_listing": {
        "id": "上市映射的 UUID 标识。", "security_id": "关联证券主数据 ID。",
        "stock_symbol_id": "既有股票记录 ID，一条股票记录仅有一个发行主体映射。",
        "market": "映射建立时的市场代码。", "symbol": "映射建立时的股票代码。", "name": "映射建立时的证券名称。",
        "evidence_id": "支持发行主体映射的持久证据版本 ID。", "created_at": "映射建立时刻。",
    },
    "foundation_evidence": {
        "id": "持久证据版本的 UUID 标识。", "entity_id": "可选关联主体 ID。", "source_name": "实际来源名称。",
        "source_key": "同一来源文档的稳定键，用于组织更正版本。", "title": "证据标题。",
        "content": "提交或导入的完整文本；是否属于原始全文由元数据明确。", "url": "原始来源链接。",
        "published_at": "来源披露时刻，未知时为空。", "available_at": "资料可获知时刻，未知时使用本次记录时间。",
        "content_hash": "保存文本的 SHA256，用于校验原文。", "fingerprint": "文本及重要来源元数据的版本指纹。",
        "version": "同源同文档键的递增版本号。", "metadata_json": "内容范围、截断情况、旧记录来源及可获知时间依据。",
        "created_at": "本系统首次保存此版本的时刻。",
    },
    "foundation_fact": {
        "id": "事实版本的 UUID 标识。", "fact_type": "股权、控制、供应链、经济往来、分类或司法参与类型。",
        "title": "事实摘要标题。", "subject_entity_id": "事实主体的主数据 ID。", "object_entity_id": "事实客体 ID；司法参与事实为空。",
        "properties_json": "经类型契约校验的事实属性，比例、金额及司法阶段有明确口径。", "status": "审核状态，待审、已接受或已拒绝。",
        "valid_from": "业务有效期开始日期，包含当天。", "valid_to": "业务有效期结束日期，不包含当天。",
        "created_at": "系统首次记录事实的时刻。", "updated_at": "最近审核状态变更时刻。",
    },
    "foundation_fact_evidence": {"fact_id": "关联事实 ID。", "evidence_id": "关联持久证据版本 ID。"},
    "foundation_fact_review": {
        "id": "审核历史 UUID 标识。", "fact_id": "被审核的事实 ID。", "previous_status": "审核前状态。",
        "decision": "本次审核结果。", "reason": "审核理由或撤销依据。", "reviewer": "单用户应用的操作标识，不代表认证身份。",
        "created_at": "审核状态变化实际被系统记录的时刻。",
    },
    "selection_run": {"criteria_json": "本次硬过滤阈值与候选范围。", "missing_data_json": "未能获取或不足以判断的数据项。", "analysis_mode": "综合评价模式及是否请求模型。"},
    "selection_candidate": {"hard_rules_json": "可复核的量价硬规则结果。", "evidence_json": "知识库、图谱及行情证据引用。", "decision": "人工复选结果。"},
    "selection_tracking": {"required_sessions": "要求的真实交易日数量，默认十个。", "observed_sessions": "已获取的去重交易日数量。", "review_json": "完成跟踪后的复盘依据。"},
    "selection_snapshot": {"trade_date": "真实交易日行情日期。", "return_pct": "相对人工确认入场价的累计收益率。", "drawdown_pct": "相对历史峰值的回撤。"},
    "selection_decision_snapshot": {
        "id": "决策审计快照 ID。", "candidate_id": "对应选股候选 ID。", "run_id": "对应选股运行 ID。",
        "tracking_id": "对应选股跟踪 ID，可为空。", "prediction_id": "对应预测账本 ID，可为空。",
        "snapshot_kind": "快照事件类型，例如候选生成或人工审核。", "event_key": "同一事件的幂等键；不同事件保留独立快照。",
        "market": "证券市场代码。", "symbol": "证券交易代码。", "decision": "该事件时刻的候选决策状态。",
        "as_of": "决策依据对应的业务时刻。", "data_cutoff": "决策允许使用的数据截止日期。",
        "data_version": "决策使用的数据湖或数据快照版本。", "graph_version": "决策使用的知识图谱上下文版本。",
        "skill_code": "生成分析所用 Skill 业务编码。", "skill_version": "生成分析所用 Skill 版本。",
        "model_instance_code": "生成分析所用模型实例编码。", "payload_json": "候选、运行条件和决策参数的不可变快照。",
        "evidence_json": "知识库、图谱、事实、切片和血缘证据引用。", "payload_hash": "快照载荷及证据的 SHA256 哈希。",
        "created_at": "快照写入系统的时间。",
    },
    "selection_retrospective": {
        "id": "复盘记录 ID。", "snapshot_id": "关联的决策审计快照 ID。", "tracking_id": "关联的选股跟踪 ID，可为空。",
        "revision": "同一决策快照的复盘修订序号。", "market": "证券市场代码。", "symbol": "证券交易代码。",
        "status": "复盘状态，例如进行中或已完成。", "evaluated_at": "本次复盘评估时间。", "observed_sessions": "已观察的真实交易日数量。",
        "entry_price": "人工确认的入场价格。", "final_price": "本次复盘截止时的实际价格。", "return_pct": "从入场价计算的收益率。",
        "max_drawdown_pct": "跟踪期间最大回撤比例。", "target_hit": "是否达到人工确认的目标价。", "stop_hit": "是否触及人工确认的止损价。",
        "direction_hit": "实际方向是否与预测方向一致。", "attribution_json": "复盘使用的版本、证据和跟踪归因。",
        "error_tags_json": "本次复盘识别出的错误标签。", "summary": "复盘摘要。", "reviewer": "复盘执行者标识。",
        "state_hash": "当前跟踪状态的 SHA256 哈希，用于幂等和版本识别。", "created_at": "复盘版本写入时间。",
    },
    "skill_evaluation_case": {
        "id": "评测用例 ID。", "case_code": "评测用例稳定业务编码。", "task_type": "用例对应的 Skill 任务类型。",
        "description": "用例目的和背景说明。", "input_json": "提供给 Skill 的固定输入。", "expected_json": "期望输出字段和值。",
        "rubric_json": "评分规则和必填字段约束。", "dataset_version": "用例所依据的数据集版本。", "source": "用例来源，例如人工或系统生成。",
        "enabled": "是否纳入后续评测。", "created_at": "用例创建时间。", "updated_at": "用例最近更新时间。",
    },
    "skill_evaluation_run": {
        "id": "评测运行 ID。", "skill_id": "被评测的 Skill ID，可为空。", "skill_code": "被评测 Skill 的业务编码。",
        "skill_version": "被评测 Skill 的版本。", "task_type": "本次评测的任务类型。", "dataset_version": "本次评测使用的数据集版本。",
        "evaluator": "评测方式，例如规则或模型。", "status": "评测运行状态，例如运行中、通过或失败。",
        "summary_json": "用例数量、通过率和失败摘要。", "started_at": "评测开始时间。", "completed_at": "评测完成时间。",
    },
    "skill_evaluation_result": {
        "id": "评测结果 ID。", "run_id": "所属评测运行 ID。", "case_id": "对应评测用例 ID。",
        "output_json": "Skill 对该用例生成的实际输出。", "metrics_json": "逐项评分、通过数和错误标签。",
        "passed": "该用例是否通过评测。", "error_type": "失败类型，例如字段缺失或证据越界。",
        "latency_ms": "本次评测耗时，单位为毫秒。", "evidence_refs_json": "输出引用的证据 ID 列表。", "created_at": "结果写入时间。",
    },
    "stock_context_event": {
        "event_type": "外部证据类别：政策、原材料、产业链、股东、合同或其他。",
        "published_at": "原始资料发布时刻，以 UTC 存储。",
        "related_entity": "资料涉及的相关企业、机构、原料或政策名称；不代表已确认因果关系。",
        "content_hash": "来源、标题及原文的 SHA256，用于同一股票证据导入去重。",
        "content": "导入的完整文本，不自动补写原文缺失部分。",
        "source_name": "原始发布机构或数据来源名称，由导入者提供，待治理核验。",
    },
    "agent_data_asset": {
        "table_name": "该数据资产对应的本地物理表名。",
        "display_name": "数据资产在界面中显示的名称。",
    },
    "data_fetch_log": {"status": "按需抓取任务的执行状态。"},
    "data_source": {"source_name": "数据源在界面中显示的名称。"},
    "data_sync_log": {"status": "批量同步任务的执行状态。"},
    "database_table_comment": {
        "table_name": "被说明的物理数据库表名，也是本表主键。",
        "display_name": "数据库表的中文名称。",
        "description": "该数据库表的业务用途与存储内容。",
    },
    "governance_run": {"status": "本次治理任务的执行状态。"},
    "knowledge_base": {"status": "知识库的建设或使用状态。"},
    "model_call_log": {"status": "本次模型调用的执行状态。"},
    "model_skill_revision": {"source": "历史版本的产生方式，例如界面编辑或文件同步。"},
    "prediction_ledger": {"status": "预测待复盘、已评估等生命周期状态。"},
    "skill_optimization_draft": {"status": "Skill 优化草案的待审核、通过或拒绝状态。"},
    "stock_news": {"source_name": "发布新闻的媒体或来源名称。"},
    "stock_symbol": {"status": "股票上市、退市等交易状态。"},
}


def column_descriptions_for(table: Table) -> dict[str, str]:
    overrides = TABLE_COLUMN_OVERRIDES.get(table.name, {})
    actual_names = {column.name for column in table.columns}
    unknown_overrides = set(overrides) - actual_names
    if unknown_overrides:
        raise ValueError(f"{table.name} has unknown column overrides: {sorted(unknown_overrides)}")
    missing = actual_names - set(COMMON_COLUMN_DESCRIPTIONS) - set(overrides)
    if missing:
        raise ValueError(f"{table.name} has undocumented columns: {sorted(missing)}")
    return {
        column.name: overrides.get(column.name, COMMON_COLUMN_DESCRIPTIONS.get(column.name, ""))
        for column in table.columns
    }


def apply_table_comments(metadata: MetaData) -> None:
    """Expose comments in SQLAlchemy and in databases with native COMMENT support."""
    for name, table in metadata.tables.items():
        description = TABLE_DESCRIPTIONS.get(name)
        if description is not None:
            table.comment = description.description
            column_descriptions = column_descriptions_for(table)
            for column in table.columns:
                column.comment = column_descriptions[column.name]


def seed_table_comments(session: Session) -> None:
    """Keep the queryable SQLite catalog in sync without touching business rows."""
    from app.models.schema_catalog import DatabaseTableComment
    from app.db.base import Base

    for name, description in TABLE_DESCRIPTIONS.items():
        row = session.get(DatabaseTableComment, name)
        if row is None:
            row = DatabaseTableComment(table_name=name)
            session.add(row)
        row.display_name = description.display_name
        row.domain = description.domain
        row.description = description.description
        row.column_comments_json = column_descriptions_for(Base.metadata.tables[name])
    session.commit()
